### ISSUE TITLE
Remove rgeo or georuby and update dev:prime to use  the winner

### ISSUE THREAD

**Issue by teknofire** [gina-alaska/awrvi#143]
Well, I missed seeing that we had rgeo already in the system when I added georuby so we should decide which one we want and remove the other!

I'm leaning towards just using georuby as it implements just what we want, while rgeo has a bunch of other stuff to handle reprojections on the fly and what not that we probably won't ever use for this project.

**Comment by smacfarlane** [comment]
+1 for georuby

**Comment by grimm** [comment]
I don't have a preference for either one.
