### ISSUE TITLE
On creating a new index the flash message gets blocked.

### ISSUE THREAD

**Issue by grimm** [gina-alaska/awrvi#145]
After creating a new index and it gets displayed the flash message gets blocked by the edit button.  Also when deleting an index the flash message gets blocked by the side menu.

**Comment by grimm** [comment]
Looks like we need to reserve space for the message on the sidebar or move the message someplace else?

**Comment by teknofire** [comment]
This is already fixed by https://github.com/gina-alaska/awrvi/pull/142/commits/e52f5e3e46bde2b2992c01512a3d5a924a44b0fa
