### ISSUE TITLE
Adminstrator / Expert Reviewer role

### ISSUE THREAD

**Issue by vlraymond** [gina-alaska/awrvi#163]
this role can give a "expert reviewed" approval, which is visible and searchable

**Comment by grimm** [comment]
Is there a possibility that there might be more than one reviewer?  I have set things up so that will not be a problem, but it will affect how this information is displayed.

**Comment by vlraymond** [comment]
I think it is possible there may be more than one, however unlikely that
more than one reviewer would approve the same dashboard.

**Comment by teknofire** [comment]
@grimm lets just make sure to do this as a separate resource.  I think overall that will be cleaner and potentially provide more flexibility down the road.
