### ISSUE TITLE
insert a 0 and 1 into dashboard slider

### ISSUE THREAD

**Issue by vlraymond** [gina-alaska/awrvi#164]
or more generally display the context for the user

**Comment by teknofire** [comment]
This is to show the min and max values of the progressbars

**Comment by grimm** [comment]
Should this be 0 to 100 for percentage?

**Comment by smacfarlane** [comment]
I have a problem with 0 and 1.  From the users perspective, those are completely arbitrary numbers that don't convey any more meaning than no labels.  

I would think using text descriptions like 'highly vulnerable' would be much more clear to the users.

**Comment by teknofire** [comment]
Yeah, I don't think 0 - 1 or even 0 - 100 would be necessarily correct for these.  The key thing is to give a more clear indication of the meaning for the bars.  Something as simple as "More vulnerable" and "Less vulnerable" on each side of it would seems to be what I would want to see.
