### ISSUE TITLE
deploy changes made in #192

### ISSUE THREAD

**Issue by vlraymond** [gina-alaska/awrvi#193]
help we need Will #heroku #deployhow? #keytocastle

**Comment by onudson** [comment]
I've invited Dayne as an admin to the awrvi heroku account.  I'll drop the heroku@gina.alaska.edu login password into chef vault.  @vlraymond, do you have that password already?

**Comment by onudson** [comment]
heroku credentials are now in chef vault secrets_vault on OIT local chef server.

**Comment by vlraymond** [comment]
I don't think I do. If I did, I forgot.

Project Manager
Geographic Information Network of Alaska
*a part of the Geophysical Institute at University of Alaska Fairbanks*
http://gina.alaska.edu
http://www.alaskamapped.org
http://uafgina.tumblr.com/
