### ISSUE TITLE
Create a how-to pdf on AWRVI indexes

### ISSUE THREAD

**Issue by teknofire** [gina-alaska/awrvi#31]
This should include a list of the information they will need to gather in order to create a index entry.

**Comment by grimm** [comment]
This is already an issue #5

**Comment by teknofire** [comment]
This is different from #5.  This is the ticket for creating the PDF while #5 is the ticket for adding the PDF to the AWRVI application.

**Comment by vlraymond** [comment]
I assumed the how-to went on the website, not the app.

**Comment by grimm** [comment]
They are both one and the same.  :D

**Comment by vlraymond** [comment]
This task is now taken by an AWRVI research student. It is off my plate!
