### ISSUE TITLE
A user should be able to start a new index for a community.

### ISSUE THREAD

**Issue by grimm** [gina-alaska/awrvi#8]
A user should be able to start a new index for a community.

**Comment by teknofire** [comment]
Is this already done?

**Comment by grimm** [comment]
I don't think so.  You can create an index through the index controller, but shouldn't this happen through the community controller?

**Comment by teknofire** [comment]
We need to make sure we have the workflow correct for this.  The new indexes should be started from the community page and the route should be reflected to handle this.  Also make sure to remove the new index link from the Indicies controller -> index action.
