### ISSUE TITLE
Handle permission denied errors

### ISSUE THREAD

**Issue by grimm** [gina-alaska/awrvi#92]
CanCanCan permission denied errors need to be handled so that they either log the user in, or redirect them with flash error.

**Comment by teknofire** [comment]
Need to handle this so it can catch the requested url

if user is not logged in, redirect to the login stuff and then take them back to the original URL requested.

if user is logged in and still don't have permission redirect back to home with a flash error message about not having permissions

**Comment by teknofire** [comment]
If we handle it this way we really don't need to do anything special on pages that require a user to sign in for creating a new community index. 

We may just need add a note under the button that they will be asked to login if they currently not logged in.
