### ISSUE TITLE
Update the communities show actions

### ISSUE THREAD

**Issue by teknofire** [gina-alaska/awrvi#98]
We need to update the community show page to  handle different viewing scenarios.

If there is are no finalized indexes for the community we should show a message about starting a new one.

If there is an index show render the dashboard for the latest finalized index.

**Comment by grimm** [comment]
Is this the same as issue #8?

**Comment by teknofire** [comment]
No, completely different.  #8 is about starting a new index for a community.  This is about showing the community, it's info and any indexes that have been created for that community. 

That being said we need to wait on doing this until #8 and #107 are done
